# Generated by Django 3.2.7 on 2021-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb1', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default='no comments', max_length=2000),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='anon', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='no comments', max_length=225),
        ),
    ]
